out_dir: tests/results
metric_best: ap
wandb:
  use: True
  project: peptides-func
  entity: tum_i26
dataset:
  format: OGB
  name: peptides-functional
  task: graph
  task_type: classification_multilabel
  transductive: False
  node_encoder: True
  node_encoder_name: Atom+MagLapPE+RWSE
  node_encoder_bn: False
  edge_encoder: True
  edge_encoder_name: Bond
  edge_encoder_bn: False
posenc_MagLapPE:
  enable: True
  positional_encoding: True
  dim_pe: 8
  q: 0.
  largest_connected_component: False
  sparse: False
  max_freqs: 150
posenc_RWSE:
  enable: True
  kernel:
    times_func: range(1,21)
  model: Linear
  dim_pe: 28
  raw_norm_type: BatchNorm
train:
  mode: custom
  batch_size: 200
  eval_period: 1
  ckpt_period: 100
model:
  type: s2gnn
  loss_fun: cross_entropy
  edge_decoding: dot
  graph_pooling: mean
gnn:
  head: mlp_graph
  layers_pre_mp: 0
  layers_mp: 3
  layers_post_mp: 3
  dim_inner: 224
  layer_type: gcnconv
  stage_type: stack
  batchnorm: False
  act: gelu
  dropout: 0.25
  agg: mean
  spectral:
    layer_skip: [3]
    frequency_cutoff: 0.7
    filter_encoder: basis # basis, lin, mlp or attn
    feature_transform: glu_0.05
    filter_variant: None  # None, silu or silu_mix
    window: tukey
    basis_num_gaussians: 60
    basis_bottleneck: 0.2
    num_heads_filter_encoder: 128
optim:
  clip_grad_norm: True
  optimizer: adamW
  weight_decay: 0.0035
  base_lr: 0.00225
  max_epoch: 250
  scheduler: cosine_with_warmup
  num_warmup_epochs: 5
share:
  dim_in: 236
device: cuda
